name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ðŸ“¦ Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø­Ø§Ù„Ø© ÙˆØ§Ù„ØªØ®Ø²ÙŠÙ† Ø§Ù„Ù…Ø¤Ù‚Øª
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1


  # ðŸ“¦ Ø§Ù„ÙˆØµÙˆÙ„ Ø¥Ù„Ù‰ Ø§Ù„Ù…Ø³Ø§Ø±Ø§Øª
  path_provider: ^2.1.2

  # ðŸ“¦ Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±Ø§Øª Ø§Ù„Ù…Ø­Ù„ÙŠØ©
  flutter_local_notifications: ^19.0.0

  # ðŸŒ Ø¯Ø¹Ù… Ø§Ù„ØªØ±Ø¬Ù…Ø©
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # ðŸ“· Ø§Ù„ØªÙ‚Ø§Ø· Ø§Ù„ØµÙˆØ±
  image_picker: ^1.0.7

  # ðŸŽ¨ Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª iOS
  cupertino_icons: ^1.0.2

  # ðŸ”¥ Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/laptop.png
    - assets/books.png
    - assets/stethoscope.png
    - assets/labcoat.png
    - assets/shopping_bag.png
    - assets/bag_icon.png
    - assets/emoji_amazing.png
    - assets/emoji_bad.png
    - assets/emoji_good.png
    - assets/emoji_ok.png